import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar'


export default function Home() {
  return (
    <>
     <style jsx>
        {
          `
          .mySpan{
            color: red 
          }`
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Lets Start Blogging&nbsp;
            <code className={styles.code}>Click To Continue</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>


        <div className={styles.center}>
          <h1> &lt;HuntingCoder/&gt;</h1>
         
        </div>
        <div className={styles.imagewrap} >
        <Image className={styles.myImg} src="/coderImages.png" width={237} height={158} />
         
        </div>
       
        <h2>Latest Blogs</h2>
        <div className={styles.grid}>
          <a>
              <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic...</p>
            <button className={styles.btn}>Read More</button>
          </a>

          <a>
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic...</p>
            <button className={styles.btn}>Read More</button>
          </a>

          <a>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic...</p>
            <button className={styles.btn}>Read More</button>
          </a>

  
        </div>
      </main>
    </>
  )
}
